// <auto-generated />
using System;
using INTEX.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INTEX.API.Migrations
{
    [DbContext(typeof(MovieDbContext))]
    partial class MovieDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.14");

            modelBuilder.Entity("INTEX.API.Data.Movie", b =>
                {
                    b.Property<string>("show_id")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Action")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Adventure")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AnimeSeriesInternationalTVShows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("BritishTVShowsDocuseriesInternationalTVShows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Children")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Comedies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComediesDramasInternationalMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComediesInternationalMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ComediesRomanticMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("CrimeTVShowsDocuseries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Documentaries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DocumentariesInternationalMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Docuseries")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dramas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DramasInternationalMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DramasRomanticMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("FamilyMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Fantasy")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HorrorMovies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InternationalMoviesThrillers")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("InternationalTVShowsRomanticTVShowsTVDramas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("KidsTV")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LanguageTVShows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Musicals")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NatureTV")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("RealityTV")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Spirituality")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TVAction")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TVComedies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TVDramas")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TalkShowsTVComedies")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Thrillers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("cast")
                        .HasColumnType("TEXT");

                    b.Property<string>("country")
                        .HasColumnType("TEXT");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<string>("director")
                        .HasColumnType("TEXT");

                    b.Property<string>("duration")
                        .HasColumnType("TEXT");

                    b.Property<string>("rating")
                        .HasColumnType("TEXT");

                    b.Property<int?>("release_year")
                        .HasColumnType("INTEGER");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("show_id");

                    b.ToTable("Movies");
                });

            modelBuilder.Entity("INTEX.API.Data.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Age")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AmazonPrime")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("AppleTVPlus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("City")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("DisneyPlus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Hulu")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("Max")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Netflix")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("ParamountPlus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Peacock")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.Property<string>("State")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Zip")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
